import { useParams, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ChevronLeft } from "lucide-react";
import { TestCaseGenerateForm } from "@/components/test-cases/TestCaseGenerateForm";

export default function TestCaseGenerate() {
  const { agentId, versionId } = useParams();
  if (!agentId || !versionId) return null;
  return (
    <div className="p-6 max-w-3xl mx-auto">
      <Button asChild variant="ghost" size="sm" className="mb-3">
        <Link to={`/agents/${agentId}`}>
          <ChevronLeft className="w-4 h-4" />
          Back to agent
        </Link>
      </Button>
      <h1 className="text-lg font-semibold mb-1">Configure & generate test cases</h1>
      <p className="text-[11px] text-muted-foreground mb-5">
        Test cases are generated by the backend AI from this version's contract.
        Adjust the count below.
      </p>
      <TestCaseGenerateForm agentId={agentId} versionId={versionId} />
    </div>
  );
}
